
GET http://localhost:4000/api/persons

###
POST http://localhost:4000/api/persons
Content-Type: application/json

{
    "name": "tim",
    "number": "894562",
    "content": "New Nogyuhte",
    "important": true
}

###
GET  http://localhost:4000/info/

###
DELETE http://localhost:4000/api/persons/3